#!/usr/bin/bash

source "$BRUTIL"

export IO_TARGET="$HOME/.bashrc"

if ! have_entry_st '# command alias for barroit'
then
	write_entry '# command alias for barroit'

	while read line
	do
		entry=$(awk '{
				cmd = $1;
				$1 = "";
				print "alias " cmd "='\''" substr($0, 2) "'\''";
			}' <<< $line)
		write_entry_r "$entry"
	done < alias.list

	source "$IO_TARGET"
fi
