#!/usr/bin/bash

minimal_perl_version='v5.38'
perl_version=$(perl --version | grep -oP 'v\d\.\d+\.\d')

if [[ -z $perl_version || $perl_version < $minimal_perl_version ]]
then
	echo "perl version $perl_version does not meet the requited version $minimal_perl_version" >&2
	exit 1
fi

if [[ -r ./README ]] && grep 'autoconfig' ./README > /dev/null
then
:
else
	echo 'make sure you are in the project root dir'
	exit 1
fi

perl ./start-mapping
