#!/usr/bin/bash

source "$BRUTIL"

export IO_TARGET="$HOME/.bashrc"

if ! have_entry_st 'ulimit -c unlimited'
then
	write_entry 'ulimit -c unlimited'
	source "$HOME/.bashrc"
fi

export IO_TARGET='/etc/sysctl.d/br-core-dump.conf'

if ! have_entry 'kernel.core_uses_pid = 0' &&
    ! have_entry 'kernel.core_pattern = core.%e'
then
	write_entry_su_r 'kernel.core_uses_pid = 0'
	write_entry_su_r 'kernel.core_pattern = core.%e'

	sudo service procps force-reload
fi
