#!/usr/bin/bash

srcdir="$(cd $(dirname $0) &> /dev/null && pwd)/src"

for srcname in $(ls -A $srcdir)
do
	src="$srcdir/$srcname"

	eval "destdir=$(sed -n '2p' $src | awk '{print $2}')"
	dest="$destdir/$srcname"

	mkdir -p $destdir
	ln -sf $src $dest
done