#!/usr/bin/bash

commands=('mount' 'ls' 'unmount')
command="${1:-mount}"

if ! printf '%s\0' "${commands[@]}" | grep -Fxqz -- "$command"
then
	echo 'Usage: onedrive <command>

   mount     mount the remote as filesystem on a mountpoint.
   unmount   unmount the mountpoint in filesystem
   ls        list all directories of remote'
	exit 1
fi

if [[ $command == 'unmount' ]]
then
	# readarray -t mountpoints < <(mount | grep rclone | awk '{print $3"/"}')
	for mountpoint in $(mount | grep rclone | awk '{print $3"/"}')
	do
		fusermount -u $mountpoint
	done
	exit 0
fi

targets=$(rclone lsf --dirs-only onedrive:)

if [[ $command == 'ls' ]]
then
	printf '%s\n' "$targets"
	exit 0
fi

for target in $targets
do
	pathname="$HOME/$target"

	mkdir -p $pathname
	rm -rf $pathname/*

	rclone mount onedrive:$target $pathname --vfs-cache-mode full --daemon
done