#!/usr/bin/bash

commands=('mount' 'ls' 'unmount')
cmdname="${1:-mount}"


for command in "${commands[@]}"
do
	if [[ "$command" == "$cmdname" ]]
	then
		is_cmdname=1
	fi
done

if [[ -z "$is_cmdname" ]]
then
	cat << EOF
Usage: onedrive <command>

   mount     mount the remote as filesystem on a mountpoint.
   unmount   unmount the mountpoint in filesystem
   ls        list all directories of remote'
EOF
	exit 1
fi

if [[ "$cmdname" == 'unmount' ]]
then
	for mountpoint in $(mount | grep rclone | awk '{print $3"/"}')
	do
		fusermount -u "$mountpoint"
	done
	exit 0
fi

rddirs=$(rclone lsf --dirs-only onedrive:)

if [[ "$cmdname" == 'ls' ]]
then
	echo ${rddirs[@]}
	exit 0
fi

for dir in ${rddirs[@]}
do
	pathname="$HOME/$dir"

	mkdir -p "$pathname"

	if [[ $(ls -A "$pathname" | wc -l) -gt 0 ]]
	then
		echo "contents found in $pathname, remove? [y/N]"
		read -r should_remove

		case "$response" in
		[yY][eE][sS]|[yY])
			rm -rf "$pathname"/*
			;;
		*)
			continue
			;;
		esac
	fi

	rclone mount onedrive:$dir $pathname --vfs-cache-mode full --daemon
done
