#!/usr/bin/bash

source "$BRUTIL"

cat << EOF
Following the default instructions illustrated on https://rclone.org/onedrive/.
The config profile needs to be named 'onedrive'.
EOF

notify_user

rclone config

require_success

export IO_TARGET="$HOME/.bashrc"

if ! have_entry "export REMOTE_FILESYS='onedrive'"
then
	write_entry "export REMOTE_FILESYS='onedrive'"
	source "$HOME/.bashrc"
fi
