#!/usr/bin/bash

source "$BRUTIL"

export IO_TARGET="$HOME/.config/user-tmpfiles.d/oneshot.conf"
TMPDIR='/tmp/barroit-oneshot'

if ! have_entry "d $TMPDIR 0700 $USER $USER -"
then
	write_entry "d $TMPDIR 0700 $USER $USER -"

	systemd-tmpfiles --create "$IO_TARGET"
fi

if ! have_entry "e! $TMPDIR - - - 0"
then
	write_entry "e! $TMPDIR - - - 0"
fi

export IO_TARGET="$HOME/.bashrc"

if ! have_entry "export BRONESHOT='$TMPDIR'"
then
	write_entry "export BRONESHOT='$TMPDIR'"

	source "$IO_TARGET"
fi
