#!/usr/bin/env perl

use v5.38;
use Env qw(HOME);
use autodie;

my $file = "$HOME/.bashrc";

open my $fh_out, '<', $file;

my @lines = <$fh_out>;

close $fh_out;

my %aliases = (
	add => 'git add -A',
	commit => 'git commit -as',
	push => 'git push',
	make => 'make -j25',
	vi => 'vim',
	codeln => 'git ls-files | xargs wc -l',
	'codeln-digest' => 'git ls-files | xargs cat | wc -l'
);

open my $fh_in, '>>', $file;

if (@lines && $lines[-1] !~ /\n$/)
{
	print $fh_in "\n";
}

while(my ($alias, $command) = each %aliases)
{
	if (! grep { /^alias $alias=.+/ } @lines)
	{
		say $fh_in "alias $alias='$command'";
	}
}
