#!/usr/bin/bash

spinner()
{
	local pid=$!
	local emoji=' >_<'
	local i=0
	local r=true

	stty -echo

	while kill -0 $pid 2>/dev/null && $r
	do
		i=$(((i + 1) % 4))

		if [[ $i -eq 0 ]]
		then
			printf '\r   \r'
		else
			printf '%s' "${emoji:$i:1}"
		fi

		read -t $(echo "($i + 1) * 0.3" | bc -l) -n 1 input
		if [[ -n "$input" ]]
		then
			kill $pid
			echo -e '\r>_<'
			r=false
		fi
	done

	stty echo
}

bash -c 'while true; do sleep 60; done' & spinner