#!/usr/bin/bash

source "$BRUTIL"

command="${1:-import}"

case "$command" in
import)
	dconf load /org/gnome/terminal/legacy/profiles:/ <\
		"$ROOT/config/gnome.term"
	;;
export)
	dconf dump /org/gnome/terminal/legacy/profiles:/ >\
		"$ROOT/config/gnome.term"
	;;
*)
	error "unknown command '$command'"
	exit 1
esac
