# SPDX-License-Identifier: GPL-3.0-only

RED='\033[0;31m'
YELLOW='\033[0;33m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
WHITE='\033[0;37m'
RESET='\033[0m'

CURSCR=$(basename $1)

die()
{
	>&2 echo -en "${RED}fatal${RESET}: "
	>&2 echo $*
	exit 128
}

error()
{
	>&2 echo -en "${RED}error${RESET}: "
	>&2 echo $*
	return 1
}

warn()
{
	>&2 echo -en "${YELLOW}warning${RESET}: "
	>&2 echo $*
	return 1
}

note()
{
	echo -en "${WHITE}note: "
	echo -n  $*
	echo -e  "${RESET}"
}

exit_on_error()
{
	if [[ $? -ne 0 ]]; then
		exit 128
	fi
}

flex_tee()
{
	local file=$1

	if [[ $SUPERUSER ]]; then
		sudo tee -a $file
	else
		tee -a $file
	fi
}

echo_line_sep()
{
	echo "------------------- $* -------------------"
}

echo_linked()
{
	printf "${CYAN}%-25s${RESET} -> ${GREEN}%s${RESET}\n" "$1" "$2"
}

no_space()
{
	if [[ $(echo $* | wc -w) != '1' ]]; then
		return 1
	fi
}

__initwr=1
write_on_missing()
{
	local text=$1
	local file=$IOTARGET
	local prompt="$COMMENT generated by $CURSCR"

	if [[ -z "$file" ]]; then
		die "IOTARGET ‘$IOTARGET’ is empty"
	elif ! no_space $file; then
		die "path ‘$file’ contains space"
	fi

	if grep -sq "^[[:space:]]*$text[[:space:]]*$" $file; then
		skipped=1
		return
	fi

	if [[ $__initwr ]]; then
		echo_line_sep $CURSCR
		__initwr=
	fi

	if [[ ! -f $file || $(wc -w < $file) = '0' ]]; then
		mkdir -p $(dirname $file)
		exit_on_error

		echo -n      | flex_tee $file
	else
		if [[ $SUPERUSER ]]; then
			sudo perl -0777 -pi -e 's/\n+\z/\n\n/' $file
		else
			perl -0777 -pi -e 's/\n+\z/\n\n/' $file
		fi
	fi

	echo $prompt | flex_tee $file > /dev/null
	echo $text   | flex_tee $file > /dev/null
	printf '>%s	%s\n' $file "$text"
}

waiting_user()
{
	echo $*

	echo Press any key to continue...
	read -sN1
}

skip_line()
{
	if [[ -z "$1" || "$1" =~ ^#.* ]]; then
		return 0
	fi

	return 1
}

find_word()
{
	for word in "${@:2}"; do
		if [[ "$1" == "$word" ]]; then
			return 0
		fi
	done

	return 1
}

source $1
