#!/usr/bin/bash
# $HOME/

DEFAULT_TIMEOUT=1800
CACHE_FILE="$HOME/.cache/keeprun/pid"

timeout="$DEFAULT_TIMEOUT"

if [[ $1 =~ '^[0-9]+$' ]]; then
	timeout=$1
elif [[ $1 == 'stop' ]]; then
	is_stop=1
elif [[ ! $1 ]]; then
	:
else
	echo "unknown argument: $1"
	exit 1
fi

if [[ $is_stop ]]; then
	if [[ ! -f $CACHE_FILE ]]; then
		echo "missing cache file: $CACHE_FILE"
		exit 1
	fi

	kill $(cat $CACHE_FILE)
	echo "stopped program: $CACHE_FILE"
	rm $CACHE_FILE
	exit 0
fi

mkdir -p $(dirname $CACHE_FILE)

if [[ -f $CACHE_FILE ]]; then
	kill $(cat $CACHE_FILE)
fi

systemd-inhibit --what=sleep --who="AFK" --why="no why" sleep $timeout &

echo $! > $CACHE_FILE
cat $CACHE_FILE
